### PR TITLE
Fix #11, also add sampler for Cognito

### LINKED ISSUE #11: Does not work without profile, even if key/secret/etc are already provided in sampler parameters
I set the correct aws_access_key_id, aws_secret_access_key, aws_region and sqs_queue_name in SQSProducerFifoQueue parameters, this should be enough to send a message to SQS, but I was unable to do so due to error:

```
software.amazon.awssdk.core.exception.SdkClientException: Unable to load region from any of the providers in the chain software.amazon.awssdk.regions.providers.DefaultAwsRegionProviderChain@1886ab0a: [software.amazon.awssdk.regions.providers.SystemSettingsRegionProvider@47562565: Unable to load region from system settings. Region must be specified either via environment variable (AWS_REGION) or  system property (aws.region)., software.amazon.awssdk.regions.providers.AwsProfileRegionProvider@1a67aa6: No region provided in profile: default, software.amazon.awssdk.regions.providers.InstanceProfileRegionProvider@16549e69: Unable to contact EC2 metadata service.]
	at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:98) ~[awsmeter-2.1.1.jar:?]
	at software.amazon.awssdk.regions.providers.AwsRegionProviderChain.getRegion(AwsRegionProviderChain.java:70) ~[awsmeter-2.1.1.jar:?]
	at org.apache.jmeter.protocol.aws.AWSClient.getAWSRegion(AWSClient.java:35) ~[awsmeter-2.1.1.jar:?]

```

The reason seems to be that in `AWSClient.getAWSRegion()`, it's using `orElse()` which will execute the `getDefaultAwsRegionProviderChain`/`getRegion()` even if AWS region is already provided in `credentials`. It should be using `orElseGet()` instead.

The same problem exists in `AWSClient.getAWSAccessKeyId()` and `AWSClient.getAWSSecretAccessKey()` as well.

Once this is fixed, there is another issue that prevents me from using the sampler without a profile: if no session token is provided in credentials, `AWSClient.getAWSSessionToken()`'s `orElseGet()` will be run, it will throw exception if there's no profile. This should be changed so that if an exception is thrown, `getAWSSessionToken()` will return null, so that `AWSClientSDK2.getAwsCredentialsProvider()` will use basic credentials instead.

### PR DESCRIPTION
**Pull request by jraoatlogic**
This should fix #11, I also added sampler for Cognito so that you can create user in Cognito and login to Cognito using existing user to obtain tokens.

### CODE REVIEW

File: src/main/java/org/apache/jmeter/protocol/aws/cognito/CognitoProducerAdminCreateUser.java [hunk 1]
```diff
@@ -0,0 +1,111 @@
...
+        } catch (JsonProcessingException exc) {
+            log.error("Unable to create user " + context.getParameter(COGNITO_USER_USERNAME), exc);
+            sampleResultFail(result, FAIL_CODE, exc.getMessage());
+        }
+
+        return result;
+    }
+    
+    protected AdminCreateUserRequest createAdminCreateUserRequest(JavaSamplerContext context) 
+            throws JsonProcessingException {
```
Comment (JoseLuisSR) [inline src/main/java/org/apache/jmeter/protocol/aws/cognito/CognitoProducerAdminCreateUser.java:88]: You can remove the throw statement because the code is not deserializing JSON string to Java object.

File: src/main/java/org/apache/jmeter/protocol/aws/cognito/CognitoProducerAdminCreateUser.java [hunk 2]
```diff
@@ -0,0 +1,111 @@
...
+        return AdminCreateUserRequest.builder()
+                .userPoolId(context.getParameter(COGNITO_USER_POOL_ID))
+                .username(context.getParameter(COGNITO_USER_USERNAME))
+                .userAttributes(attributeType)
+                .messageAction("SUPPRESS")
+                .build();
+    }
+    
+    protected AdminSetUserPasswordRequest createAdminSetUserPasswordRequest(JavaSamplerContext context) 
+            throws JsonProcessingException {
```
Comment (JoseLuisSR) [inline src/main/java/org/apache/jmeter/protocol/aws/cognito/CognitoProducerAdminCreateUser.java:103]: You can remove the throw statement because the code is not deserializing JSON string to Java object.

File: src/main/java/org/apache/jmeter/protocol/aws/cognito/CognitoProducerAdminCreateUser.java [hunk 3]
```diff
@@ -0,0 +1,111 @@
...
+        try{
+            log.info("Create user in Cognito");
+            AdminCreateUserResponse createUserRsp = cognitoClient.adminCreateUser(createAdminCreateUserRequest(context));
+            cognitoClient.adminSetUserPassword(createAdminSetUserPasswordRequest(context)); // this will also set user status to confirmed
+            
+            sampleResultSuccess(result, String.format("User Attributes: %s", createUserRsp.user().attributes()));            
+        } catch (CognitoIdentityProviderException exc){
+            log.error("Unable to create user " + context.getParameter(COGNITO_USER_USERNAME), exc);
+            sampleResultFail(result, exc.awsErrorDetails().errorCode(), exc.awsErrorDetails().errorMessage());
+        } catch (JsonProcessingException exc) {
```
Comment (JoseLuisSR) [inline src/main/java/org/apache/jmeter/protocol/aws/cognito/CognitoProducerAdminCreateUser.java:79]: You can remove the throw statement because the code is not deserializing JSON string to Java object.

File: src/main/java/org/apache/jmeter/protocol/aws/cognito/CognitoProducerAdminCreateUser.java [hunk 4]
```diff
@@ -0,0 +1,111 @@
...
+import java.util.List;
+import java.util.stream.Collectors;
+import java.util.stream.Stream;
+
+import org.apache.jmeter.config.Argument;
+import org.apache.jmeter.config.Arguments;
+import org.apache.jmeter.protocol.java.sampler.JavaSamplerContext;
+import org.apache.jmeter.samplers.SampleResult;
+
+import com.fasterxml.jackson.core.JsonProcessingException;
```
Comment (JoseLuisSR) [inline src/main/java/org/apache/jmeter/protocol/aws/cognito/CognitoProducerAdminCreateUser.java:12]: When removing the JsonProcessingException statements then you can remove unused imports.

**Comment by jraoatlogic** [comment]
Ok, these 4 changes have been done.

File: src/main/java/org/apache/jmeter/protocol/aws/cognito/CognitoProducerAdminLoginUser.java [hunk 5]
```diff
@@ -0,0 +1,125 @@
...
+        } catch (GeneralSecurityException exc) {
+            log.error("Unable to login user " + context.getParameter(COGNITO_USER_USERNAME), exc);
+            sampleResultFail(result, FAIL_CODE, exc.getMessage());
+        }
+
+        return result;
+    }
+    
+    protected AdminInitiateAuthRequest createAdminInitiateAuthRequest(JavaSamplerContext context) 
+            throws JsonProcessingException, GeneralSecurityException {
```
Comment (JoseLuisSR) [inline src/main/java/org/apache/jmeter/protocol/aws/cognito/CognitoProducerAdminLoginUser.java:112]: Please remove the JsonProcessingException.

File: src/main/java/org/apache/jmeter/protocol/aws/cognito/CognitoProducerAdminLoginUser.java [hunk 6]
```diff
@@ -0,0 +1,125 @@
...
+                .ifPresent(varName -> context.getJMeterVariables().put(varName, authResult.idToken()));
+            Optional.ofNullable(context.getParameter(COGNITO_USER_REFRESH_TOKEN_VAR_NAME))
+                .filter(not(String::isBlank))
+                .ifPresent(varName -> context.getJMeterVariables().put(varName, authResult.refreshToken()));
+            
+            sampleResultSuccess(result, String.format("Auth Result: %s", loginUserRsp.authenticationResult()));            
+        } catch (CognitoIdentityProviderException exc){
+            log.error("Unable to login user " + context.getParameter(COGNITO_USER_USERNAME), exc);
+            sampleResultFail(result, exc.awsErrorDetails().errorCode(), exc.awsErrorDetails().errorMessage());
+        } catch (JsonProcessingException exc) {
```
Comment (JoseLuisSR) [inline src/main/java/org/apache/jmeter/protocol/aws/cognito/CognitoProducerAdminLoginUser.java:100]: Please remove the catch of JsonProcessingException.

File: src/main/java/org/apache/jmeter/protocol/aws/cognito/CognitoProducerAdminLoginUser.java [hunk 7]
```diff
@@ -0,0 +1,125 @@
...
+import java.util.Optional;
+import java.util.stream.Collectors;
+import java.util.stream.Stream;
+
+import org.apache.jmeter.config.Argument;
+import org.apache.jmeter.config.Arguments;
+import org.apache.jmeter.protocol.java.sampler.JavaSamplerContext;
+import org.apache.jmeter.samplers.SampleResult;
+
+import com.fasterxml.jackson.core.JsonProcessingException;
```
Comment (JoseLuisSR) [inline src/main/java/org/apache/jmeter/protocol/aws/cognito/CognitoProducerAdminLoginUser.java:18]: Remove unused import when remove the JsonProcessingException statements.

**Review by JoseLuisSR — COMMENTED** [review]
Hi @jraoatlogic 

The PR looks very good.

Could you please add README.md with details about how to use the JavaSamplers to Create User and Login Use?

Thank you.

**Comment by jraoatlogic** [comment]
Ok, removed the remaining reference to JsonProcessingException, also added a simple README.md based on the one from SQS Sampler.

**Review by JoseLuisSR — APPROVED** [review]
Hi @jraoatlogic.

Nice job, thank you.
